In [20]:
import pandas as pd
import numpy as np

sampleData = 1500
np.random.seed(42)

data = {
    'CustomerID': [f"C{str(i).zfill(4)}" for i in range(1, sampleData+1)],
    'Age': np.random.randint(20, 60, sampleData),
    'Gender': np.random.choice(['Male', 'Female'], sampleData),
    'MembershipType': np.random.choice(['Bronze', 'Silver', 'Gold'], sampleData, p=[0.5, 0.3, 0.2]),
    'LastPurchaseAmount': np.random.randint(10, 2000, sampleData),
    'AvgResponseTime': np.random.uniform(0.5, 5.0, sampleData).round(1),
    'NumSupportTickets': np.random.randint(0, 10, sampleData),
    'Satisfaction': np.random.choice(['Satisfied', 'Unsatisfied'], sampleData, p=[0.6, 0.4])
}

In [21]:
df = pd.DataFrame(data)

In [23]:
df.head(20)

,CustomerID,Age,Gender,MembershipType,LastPurchaseAmount,AvgResponseTime,NumSupportTickets,Satisfaction
0,C0001,58,Female,Silver,1678,5.0,3,Satisfied
1,C0002,48,Male,Bronze,1376,3.7,3,Unsatisfied
2,C0003,34,Female,Silver,1458,4.0,3,Unsatisfied
3,C0004,27,Female,Silver,580,2.0,4,Satisfied
4,C0005,40,Female,Bronze,1544,4.7,1,Satisfied
5,C0006,58,Female,Bronze,866,2.9,1,Unsatisfied
6,C0007,38,Male,Gold,1010,3.8,8,Satisfied
7,C0008,42,Female,Bronze,1215,4.7,1,Satisfied
8,C0009,30,Male,Silver,467,4.9,5,Satisfied
9,C0010,30,Male,Silver,927,4.2,1,Satisfied
10,C0011,43,Male,Bronze,1884,1.9,4,Satisfied
11,C0012,55,Male,Bronze,842,4.8,3,Unsatisfied
12,C0013,59,Male,Bronze,1097,3.3,6,Unsatisfied
13,C0014,43,Male,Bronze,848,4.7,6,Satisfied
14,C0015,22,Male,Bronze,1293,3.5,5,Unsatisfied
15,C0016,41,Male,Gold,202,1.9,9,Satisfied
16,C0017,21,Male,Bronze,1688,2.2,4,Satisfied
17,C0018,43,Male,Silver,625,3.0,0,Satisfied
18,C0019,49,Female,Bronze,415,4.1,2,Unsatisfied
19,C0020,57,Female,Gold,1759,1.9,8,Satisfied

In [24]:
df.to_csv('Customer_Data.csv', index=False)